version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vhiweb123!
      MYSQL_DATABASE: vhiweb
      MYSQL_USER: vhiweb
      MYSQL_PASSWORD: vhiweb123!
    ports:
      - "8400:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # PHPMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: vhiweb123!
    ports:
      - "8500:80"
    depends_on:
      - mysql

  # Backend Express JS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    environment:
      DATABASE_HOST: root
      DATABASE_USER: root
      DATABASE_PASSWORD: vhiweb123!
      DATABASE_NAME: vhiweb
      SECRET_KEY: vhiweb
      PORT: 5000
    ports:
      - "8500:5000" # Sesuaikan dengan port yang digunakan oleh Express.js
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  # Front End Next JS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "8000:3000" # Sesuaikan dengan port yang digunakan oleh Next.js
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mysql_data:
