version: '3.8'

services:
  # MySQL service
  mysql:
    image: mysql:8.0
    container_name: vhiweb-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: vhiweb123!
      MYSQL_DATABASE: vhiweb
      MYSQL_USER: vhiweb
      MYSQL_PASSWORD: vhiweb123!
    ports:
      - "8201:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1'  # Maksimal 1 CPU
          memory: '512M'  # Maksimal 512MB RAM

  # PHPMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vhiweb-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: vhiweb123!
    ports:
      - "8202:80"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1'  # Maksimal 1 CPU
          memory: '512M'  # Maksimal 512MB RAM

  # Backend Express JS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vhiweb-backend
    restart: always
    environment:
      DATABASE_HOST: root
      DATABASE_USER: root
      DATABASE_PASSWORD: vhiweb123!
      DATABASE_NAME: vhiweb
      SECRET_KEY: vhiweb
      PORT: 5000
    ports:
      - "8203:5000" # Sesuaikan dengan port yang digunakan oleh Express.js
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          cpus: '1'  # Maksimal 1 CPU
          memory: '512M'  # Maksimal 512MB RAM

  # Front End Next JS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vhiweb-frontend
    restart: always
    ports:
      - "8200:3000" # Sesuaikan dengan port yang digunakan oleh Next.js
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1'  # Maksimal 1 CPU
          memory: '512M'  # Maksimal 512MB RAM

volumes:
  mysql_data:
    external: false